#!/bin/bash

min_threads=1
max_threads=24
# User can override min/max threads to use
if [ -n "$1" ]; then
  min_threads=$1
fi
if [ -n "$2" ]; then
  max_threads=$2
fi

sys_threads=$(lscpu -p | grep -v "^#" |wc -l )
if [ -z "$sys_threads" ]; then
  echo "WARNING: Cannot determine total CPUs available in system.  Assuming '$max_threads' CPUs available." >&2
  sys_threads=$max_threads
fi

load_float=$(uptime | sed -e 's|.*load average: \([0-9]\{1,\}\.[0-9]\{2\}\).*|\1|')
if [ -n "$load_float" ]; then
  load_int=$(echo "($load_float+0.5)/1" |bc) 
  threads=$(expr $sys_threads - $load_int)
  if [ $threads -lt $min_threads ]; then
    threads=$min_threads
  fi 
else
  echo "WARNING: Cannot get load average. Using job=$min_threads." >&2
  threads=$min_threads
fi 
printf $threads
