#!/bin/bash

rootDir=llvm
default_threads=8
default_sys_threads=24
default_target=llvm
makeFlags="\
buildtype=Release \
buildflags='-DLLVM_ENABLE_ASSERTIONS=ON' \
"

logfile=$(basename $0).log
sys_threads=$(lscpu -p | grep -v "^#" |wc -l )
if [ -z "$sys_threads" ]; then
  sys_threads=$default_sys_threads
fi
curDir=$(basename $PWD)

if [ $curDir != $rootDir ]; then
  echo "ERROR: Not in '$rootDir' directory."
  exit 1
fi

target=
if [ -z "$1" ]; then
  target=$default_target
fi

load_float=$(uptime | sed -e 's|.*load average: \([0-9]\{1,\}\.[0-9]\{2\}\).*|\1|')
if [ -n "$load_float" ]; then
  load_int=$(echo "($load_float+0.5)/1" |bc) 
  threads=$(expr $sys_threads - $load_int)
  if [ $threads -lt $default_threads ]; then
    threads=$default_threads
  fi 
else
  echo "WARNING: Can't get load average. Using job=$default_threads."
  threads=$default_threads
fi 
set -x
time -p make job=$threads $makeFlags $target "$@" >$logfile 2>&1
